version: '3.8'

services:
  recsys-retail:
    image: kutovaiayp/recsys-retail:service_v1
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`localhost`)"

  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/docker/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"