apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  labels:
    release: main
  name: recsys-retail  
spec:
  endpoints:
  - path: /metrics
    port: recsys-retail
    scheme: http
    interval: 60s

  jobLabel: recsys-retail
  namespaceSelector:
    matchNames:
    - recsys
  selector:
    matchLabels:
      app: recsys-retail
