apiVersion: apps/v1
kind: Deployment
metadata:
  name: recsys-retail-deployment
  labels:
    app: recsys-retail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recsys-retail
  template:
    metadata:      
      labels:
        app: recsys-retail
    spec:
      containers:
        - name: recsys-retail
          image: kutovaiayp/recsys-retail:service_v1        
          ports:
            - containerPort: 8000
