name: Docker build and push

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo v3
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |               
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . 

      - name: Train model        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}          
        run: |
          dvc pull
          scripts/train_save_model.py -o baseline_v1 -v
          
      - name: Save features in Feature store
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}          
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/ 
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp --recurvive data/02_intermediate/ s3://recsys-retail-feature-store/02_intermediate/
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp --recurvive data/03_primary/ s3://recsys-retail-feature-store/03_primary/    
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp --recurvive data/04_feature/ s3://recsys-retail-feature-store/04_feature/ 
          aws --endpoint-url=https://storage.yandexcloud.net s3 cp --recurvive data/05_model_input/ s3://recsys-retail-feature-store/05_model_input/         
      
      - name: Upload model artifact        
        uses: actions/upload-artifact@v3
        with:
          name: baseline_v1 
          path: models/baseline_v1         
          retention-days: 5

      - name: Upload features for inference        
        uses: actions/upload-artifact@v3
        with:
          name: features-for-inference
          path: data/04_feature          
          retention-days: 5

  build:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo v3
        uses: actions/checkout@v3      
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: baseline_v1
          path: models/

      - name: Download features for inference
        uses: actions/download-artifact@v3
        with:
          name: features-for-inference
          path: data/04_feature/          

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/recsys_retail/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/recsys-retail:service_v1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        