name: Docker build and push

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Train model
        run: scripts/train_save_model.py -m make_baseline_model -o baseline.v1 -v
      - name: Upload model artifact
        uses: actions/upload-artifact@v2
        with:
          name: baseline.v1
          path: models/baseline.v1.joblib
          retention-days: 5

  build:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Download model artifact
        uses: actions/download-artifact@v2
        with:
          name: baseline.v1
          path: models/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/recsys-retail/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/recsys-retail:service_v1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}