name: Python tests

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Check PEP8 compliance
        run: |
          black --check --verbose src service
      - name: Lint with mypy
        run: |
          mypy src
      - name: Unit tests with pytest
        run: |
          pytest --cov=src tests
      - name: Integration tests with pytest
        run: |
          pytest --cov=service service